// Project and apartment data with real images

// Projects data
export const projects = [
  {
    id: 1,
    name: "City Center Office Complex",
    category: "Commercial",
    location: "Downtown, Building City",
    year: "2023",
    description: "A modern 15-story office building with sustainable design features and state-of-the-art facilities.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1470&auto=format&fit=crop",
    client: "Urban Development Corp",
    size: "250,000 sq ft",
    value: "$85 million",
    fullDescription:
      "The City Center Office Complex is a landmark commercial development in the heart of downtown. This 15-story building features a striking glass facade, energy-efficient systems, and flexible office spaces designed for modern businesses. The project incorporated sustainable materials and technologies throughout, earning LEED Gold certification. The complex includes underground parking, retail spaces on the ground floor, and a rooftop garden with panoramic city views.",
    features: [
      "15 floors of premium office space",
      "LEED Gold certified sustainable design",
      "Floor-to-ceiling windows with energy-efficient glass",
      "Smart building management systems",
      "Rooftop garden and event space",
      "Ground floor retail and dining options",
      "4-level underground parking garage",
      "24/7 security and access control",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "January 2020 - June 2020",
        description: "Architectural design, engineering plans, and permit approvals.",
      },
      {
        phase: "Foundation Work",
        date: "July 2020 - October 2020",
        description: "Excavation and foundation construction for the main structure and underground parking.",
      },
      {
        phase: "Structural Construction",
        date: "November 2020 - August 2021",
        description: "Steel framework and concrete floor installation for all 15 floors.",
      },
      {
        phase: "Exterior Completion",
        date: "September 2021 - February 2022",
        description: "Installation of glass facade, roofing, and exterior finishes.",
      },
      {
        phase: "Interior Fitout",
        date: "March 2022 - December 2022",
        description: "Interior construction, MEP systems, and finishing work.",
      },
      {
        phase: "Project Completion",
        date: "January 2023",
        description: "Final inspections, commissioning, and handover to the client.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1469&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1469&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1470&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 5,
        name: "Green Valley Shopping Mall",
        category: "Commercial",
        location: "Green Valley, Building City",
        year: "2019",
        image: "https://images.unsplash.com/photo-1519567770579-c2fc5e9ca471?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 8,
        name: "Tech Innovation Hub",
        category: "Commercial",
        location: "Innovation District, Building City",
        year: "2021",
        image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=1374&auto=format&fit=crop",
      },
      {
        id: 10,
        name: "Waterfront Business Center",
        category: "Commercial",
        location: "Harbor District, Building City",
        year: "2022",
        image: "https://images.unsplash.com/photo-1577760258779-e787a1733016?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 2,
    name: "Riverside Apartments",
    category: "Residential",
    location: "Riverside District, Building City",
    year: "2022",
    description:
      "Luxury apartment complex with 120 units, featuring riverside views, swimming pools, and fitness centers.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1470&auto=format&fit=crop",
    client: "Riverside Development LLC",
    size: "180,000 sq ft",
    value: "$65 million",
    fullDescription:
      "The Riverside Apartments development is a premium residential complex situated along the scenic riverfront. The project consists of three mid-rise buildings with a total of 120 luxury apartments ranging from studios to three-bedroom units. Each building features a contemporary architectural style with extensive use of glass to maximize river views. The development includes resort-style amenities including two swimming pools, a state-of-the-art fitness center, resident lounges, and landscaped outdoor spaces. Sustainable features include solar panels, rainwater harvesting, and energy-efficient systems throughout.",
    features: [
      "120 luxury apartments across three buildings",
      "Floor plans ranging from studios to three-bedroom units",
      "Floor-to-ceiling windows with river views",
      "Two swimming pools and sun decks",
      "State-of-the-art fitness center",
      "Resident lounges and co-working spaces",
      "Landscaped gardens and walking paths",
      "Secure underground parking",
      "24/7 concierge service",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "March 2019 - September 2019",
        description: "Architectural design, engineering plans, and permit approvals.",
      },
      {
        phase: "Site Preparation",
        date: "October 2019 - December 2019",
        description: "Site clearing, grading, and utility infrastructure installation.",
      },
      {
        phase: "Foundation Work",
        date: "January 2020 - April 2020",
        description: "Foundation construction for all three buildings and underground parking.",
      },
      {
        phase: "Structural Construction",
        date: "May 2020 - February 2021",
        description: "Structural framework and floor installation for all buildings.",
      },
      {
        phase: "Exterior Completion",
        date: "March 2021 - July 2021",
        description: "Exterior cladding, windows, and roofing installation.",
      },
      {
        phase: "Interior Fitout",
        date: "August 2021 - December 2021",
        description: "Interior construction, apartment finishes, and amenity spaces.",
      },
      {
        phase: "Landscaping & Final Touches",
        date: "January 2022 - March 2022",
        description: "Landscaping, pool construction, and exterior amenities.",
      },
      {
        phase: "Project Completion",
        date: "April 2022",
        description: "Final inspections, commissioning, and opening to residents.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1380&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185008-a33f5c7b1844?q=80&w=1470&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 6,
        name: "Sunset Heights Condominiums",
        category: "Residential",
        location: "West Hills, Building City",
        year: "2018",
        image: "https://images.unsplash.com/photo-1580041065738-e72023775cdc?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 9,
        name: "Urban Loft Apartments",
        category: "Residential",
        location: "Arts District, Building City",
        year: "2020",
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 12,
        name: "Parkview Residences",
        category: "Residential",
        location: "Central Park Area, Building City",
        year: "2021",
        image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 3,
    name: "Central Hospital Expansion",
    category: "Healthcare",
    location: "Medical District, Building City",
    year: "2021",
    description:
      "A major expansion of the city's central hospital, adding 200 beds and new specialized treatment facilities.",
    image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=1473&auto=format&fit=crop",
    client: "City Health Authority",
    size: "320,000 sq ft",
    value: "$120 million",
    fullDescription:
      "The Central Hospital Expansion project involved the construction of a new six-story wing to the existing hospital facility, adding 200 patient beds and specialized treatment areas. The expansion includes new operating theaters, an expanded emergency department, diagnostic imaging center, and specialized care units. The design prioritized patient comfort, staff efficiency, and integration of advanced medical technologies. The project was completed while maintaining full operations of the existing hospital, requiring careful planning and phased construction to minimize disruption to patient care.",
    features: [
      "200 additional patient beds in private and semi-private rooms",
      "12 new state-of-the-art operating theaters",
      "Expanded emergency department with 40 treatment bays",
      "Advanced diagnostic imaging center",
      "Specialized care units for cardiac, oncology, and neurological patients",
      "Rooftop helipad for emergency medical transport",
      "Energy-efficient building systems",
      "Healing gardens and patient-centered design elements",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "January 2018 - October 2018",
        description: "Architectural design, medical planning, and regulatory approvals.",
      },
      {
        phase: "Site Preparation",
        date: "November 2018 - February 2019",
        description: "Site clearing and preparation while maintaining hospital operations.",
      },
      {
        phase: "Foundation Work",
        date: "March 2019 - July 2019",
        description: "Foundation construction for the new hospital wing.",
      },
      {
        phase: "Structural Construction",
        date: "August 2019 - May 2020",
        description: "Structural framework and floor installation for all six floors.",
      },
      {
        phase: "Exterior Completion",
        date: "June 2020 - September 2020",
        description: "Exterior cladding, windows, and roofing installation.",
      },
      {
        phase: "Interior Fitout",
        date: "October 2020 - March 2021",
        description: "Interior construction, medical equipment installation, and finishing work.",
      },
      {
        phase: "Testing & Commissioning",
        date: "April 2021 - June 2021",
        description: "Testing of all medical systems, equipment, and building systems.",
      },
      {
        phase: "Project Completion",
        date: "July 2021",
        description: "Final inspections, certification, and opening to patients.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1504439468489-c8920d796a29?q=80&w=1471&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1453&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1516841273335-e39b37888115?q=80&w=1476&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1538108149393-fbbd81895907?q=80&w=1528&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 11,
        name: "Children's Medical Center",
        category: "Healthcare",
        location: "North District, Building City",
        year: "2019",
        image: "https://images.unsplash.com/photo-1596541223130-5d31a73fb6c6?q=80&w=1374&auto=format&fit=crop",
      },
      {
        id: 13,
        name: "Medical Research Facility",
        category: "Healthcare",
        location: "University District, Building City",
        year: "2020",
        image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 14,
        name: "Wellness Center",
        category: "Healthcare",
        location: "East Side, Building City",
        year: "2022",
        image: "https://images.unsplash.com/photo-1629136571575-e7e5c6b8c3b5?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 4,
    name: "Metro Line Extension",
    category: "Infrastructure",
    location: "North District, Building City",
    year: "2020",
    description:
      "A 5-mile extension of the city's metro line, including three new stations and supporting infrastructure.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1374&auto=format&fit=crop",
    client: "City Transit Authority",
    size: "5 miles",
    value: "$350 million",
    fullDescription:
      "The Metro Line Extension project expanded the city's public transportation network with a 5-mile extension to the northern district. The project included the construction of three new underground stations, track installation, power systems, and signal infrastructure. The extension connects previously underserved neighborhoods to the city center, reducing commute times and supporting economic development in the northern district. The project incorporated sustainable design principles and state-of-the-art transit technology to enhance passenger experience and operational efficiency.",
    features: [
      "5-mile underground metro extension",
      "Three new architecturally distinctive stations",
      "Advanced signaling and control systems",
      "Energy-efficient lighting and climate control",
      "Accessibility features for all passengers",
      "Public art installations at each station",
      "Integrated bus connections and bicycle facilities",
      "Real-time passenger information systems",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "January 2016 - December 2016",
        description: "Route planning, engineering design, and environmental impact studies.",
      },
      {
        phase: "Land Acquisition",
        date: "January 2017 - June 2017",
        description: "Securing necessary land and rights-of-way for the extension.",
      },
      {
        phase: "Tunnel Boring",
        date: "July 2017 - October 2018",
        description: "Excavation of the 5-mile tunnel using tunnel boring machines.",
      },
      {
        phase: "Station Construction",
        date: "November 2017 - March 2019",
        description: "Construction of the three underground stations.",
      },
      {
        phase: "Track Installation",
        date: "April 2019 - August 2019",
        description: "Installation of tracks, power systems, and signaling infrastructure.",
      },
      {
        phase: "Systems Integration",
        date: "September 2019 - December 2019",
        description: "Integration and testing of all transit systems and technology.",
      },
      {
        phase: "Testing & Commissioning",
        date: "January 2020 - March 2020",
        description: "Comprehensive testing of trains, signals, and safety systems.",
      },
      {
        phase: "Project Completion",
        date: "April 2020",
        description: "Final inspections, certification, and opening to the public.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1565726166189-e9814a05ffde?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515695130216-1d522f1e7a28?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=1470&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 7,
        name: "Central Bridge Reconstruction",
        category: "Infrastructure",
        location: "River Crossing, Building City",
        year: "2019",
        image: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 15,
        name: "Airport Terminal Expansion",
        category: "Infrastructure",
        location: "International Airport, Building City",
        year: "2021",
        image: "https://images.unsplash.com/photo-1530521954074-e64f6810b32d?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 16,
        name: "Smart City Grid Upgrade",
        category: "Infrastructure",
        location: "Citywide, Building City",
        year: "2022",
        image: "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 5,
    name: "Green Valley Shopping Mall",
    category: "Commercial",
    location: "Green Valley, Building City",
    year: "2019",
    description:
      "A 500,000 square foot shopping mall with over 100 retail spaces, food courts, and entertainment venues.",
    image: "https://images.unsplash.com/photo-1519567770579-c2fc5e9ca471?q=80&w=1470&auto=format&fit=crop",
    client: "Valley Retail Development",
    size: "500,000 sq ft",
    value: "$95 million",
    fullDescription:
      "The Green Valley Shopping Mall is a premier retail destination featuring over 100 stores, restaurants, and entertainment venues. The two-level mall is anchored by four major department stores and includes a central atrium with natural lighting. The design emphasizes an open, airy atmosphere with extensive use of natural materials and indoor greenery. The mall includes a 12-screen cinema, food court with 20 dining options, and a children's play area. Sustainable features include solar panels on the roof, rainwater harvesting, and energy-efficient systems throughout.",
    features: [
      "500,000 square feet of retail and entertainment space",
      "Over 100 retail stores and service providers",
      "Four anchor department stores",
      "20-option international food court",
      "12-screen cinema complex",
      "Indoor children's play area",
      "Spacious central atrium with natural lighting",
      "2,000-space parking garage with EV charging stations",
      "Rooftop solar panel array",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "March 2016 - December 2016",
        description: "Architectural design, retail planning, and permit approvals.",
      },
      {
        phase: "Site Preparation",
        date: "January 2017 - April 2017",
        description: "Site clearing, grading, and utility infrastructure installation.",
      },
      {
        phase: "Foundation Work",
        date: "May 2017 - September 2017",
        description: "Foundation construction for the main structure and parking garage.",
      },
      {
        phase: "Structural Construction",
        date: "October 2017 - July 2018",
        description: "Structural framework and floor installation for all areas.",
      },
      {
        phase: "Exterior Completion",
        date: "August 2018 - November 2018",
        description: "Exterior cladding, windows, and roofing installation.",
      },
      {
        phase: "Interior Fitout",
        date: "December 2018 - March 2019",
        description: "Interior construction, common areas, and tenant spaces.",
      },
      {
        phase: "Tenant Improvements",
        date: "January 2019 - May 2019",
        description: "Individual store buildouts and customizations.",
      },
      {
        phase: "Project Completion",
        date: "June 2019",
        description: "Final inspections, grand opening ceremony, and public opening.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1581417478175-a9ef18f210c2?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1567449303078-57ad995bd17a?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555448248-2571daf6344b?q=80&w=1470&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 1,
        name: "City Center Office Complex",
        category: "Commercial",
        location: "Downtown, Building City",
        year: "2023",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 8,
        name: "Tech Innovation Hub",
        category: "Commercial",
        location: "Innovation District, Building City",
        year: "2021",
        image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=1374&auto=format&fit=crop",
      },
      {
        id: 10,
        name: "Waterfront Business Center",
        category: "Commercial",
        location: "Harbor District, Building City",
        year: "2022",
        image: "https://images.unsplash.com/photo-1577760258779-e787a1733016?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 6,
    name: "Sunset Heights Condominiums",
    category: "Residential",
    location: "West Hills, Building City",
    year: "2018",
    description: "Luxury condominium development with 80 units, featuring panoramic city views and premium amenities.",
    image: "https://images.unsplash.com/photo-1580041065738-e72023775cdc?q=80&w=1470&auto=format&fit=crop",
    client: "Hilltop Development Group",
    size: "150,000 sq ft",
    value: "$55 million",
    fullDescription:
      "Sunset Heights is an exclusive condominium development situated on the western hills of the city, offering panoramic views of the skyline and surrounding landscape. The project consists of 80 luxury units ranging from one to four bedrooms, spread across two elegant towers. Each residence features premium finishes, spacious layouts, and private balconies. The development includes resort-style amenities such as an infinity pool, fitness center, resident lounge, and landscaped gardens. The architectural design emphasizes a seamless indoor-outdoor living experience, with extensive use of glass to maximize views and natural light.",
    features: [
      "80 luxury condominium units in two towers",
      "One to four-bedroom floor plans ranging from 800 to 3,200 sq ft",
      "Floor-to-ceiling windows with panoramic city views",
      "Private balconies or terraces for each unit",
      "Infinity edge pool with city views",
      "State-of-the-art fitness center and spa",
      "Resident lounge and entertainment spaces",
      "Secure underground parking with two spaces per unit",
      "24/7 concierge and security services",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "January 2015 - September 2015",
        description: "Architectural design, engineering plans, and permit approvals.",
      },
      {
        phase: "Site Preparation",
        date: "October 2015 - December 2015",
        description: "Site clearing, grading, and utility infrastructure installation.",
      },
      {
        phase: "Foundation Work",
        date: "January 2016 - April 2016",
        description: "Foundation construction for both towers and underground parking.",
      },
      {
        phase: "Structural Construction",
        date: "May 2016 - February 2017",
        description: "Structural framework and floor installation for both towers.",
      },
      {
        phase: "Exterior Completion",
        date: "March 2017 - July 2017",
        description: "Exterior cladding, windows, and roofing installation.",
      },
      {
        phase: "Interior Fitout",
        date: "August 2017 - December 2017",
        description: "Interior construction, unit finishes, and amenity spaces.",
      },
      {
        phase: "Landscaping & Final Touches",
        date: "January 2018 - March 2018",
        description: "Landscaping, pool construction, and exterior amenities.",
      },
      {
        phase: "Project Completion",
        date: "April 2018",
        description: "Final inspections, certification, and resident move-ins.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687644-c7f34c43d2fd?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1470&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 2,
        name: "Riverside Apartments",
        category: "Residential",
        location: "Riverside District, Building City",
        year: "2022",
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 9,
        name: "Urban Loft Apartments",
        category: "Residential",
        location: "Arts District, Building City",
        year: "2020",
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 12,
        name: "Parkview Residences",
        category: "Residential",
        location: "Central Park Area, Building City",
        year: "2021",
        image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 7,
    name: "Central Bridge Reconstruction",
    category: "Infrastructure",
    location: "River Crossing, Building City",
    year: "2019",
    description: "Complete reconstruction of the city's main bridge, featuring modern design and expanded capacity.",
    image: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?q=80&w=1470&auto=format&fit=crop",
    client: "City Transportation Department",
    size: "1,200 ft length",
    value: "$180 million",
    fullDescription:
      "The Central Bridge Reconstruction project replaced the aging main bridge connecting the east and west sides of the city with a modern, architecturally distinctive structure. The new bridge features six vehicle lanes, dedicated bicycle lanes, and wide pedestrian walkways on both sides. The design incorporates a signature cable-stayed structure with two 200-foot towers that have become a new landmark for the city. The project included improvements to approach roads, new lighting systems, and landscaped areas at both ends of the bridge. Advanced engineering techniques were employed to minimize disruption to river traffic during construction.",
    features: [
      "1,200-foot cable-stayed bridge with two 200-foot towers",
      "Six vehicle lanes with capacity for 120,000 vehicles daily",
      "Protected bicycle lanes in both directions",
      "Wide pedestrian walkways with viewing platforms",
      "Architectural lighting highlighting the structure at night",
      "Advanced structural monitoring systems",
      "Improved approach roads and intersections",
      "Landscaped public spaces at bridge approaches",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "January 2016 - December 2016",
        description: "Engineering design, environmental impact studies, and permit approvals.",
      },
      {
        phase: "Temporary Structures",
        date: "January 2017 - April 2017",
        description: "Construction of temporary bridges to maintain traffic flow during reconstruction.",
      },
      {
        phase: "Demolition",
        date: "May 2017 - August 2017",
        description: "Controlled demolition of the existing bridge structure.",
      },
      {
        phase: "Foundation Work",
        date: "September 2017 - February 2018",
        description: "Construction of bridge piers and tower foundations.",
      },
      {
        phase: "Tower Construction",
        date: "March 2018 - July 2018",
        description: "Erection of the two main towers and cable systems.",
      },
      {
        phase: "Deck Installation",
        date: "August 2018 - December 2018",
        description: "Installation of bridge deck sections and roadway surface.",
      },
      {
        phase: "Finishing Work",
        date: "January 2019 - April 2019",
        description: "Installation of railings, lighting, and final road surfaces.",
      },
      {
        phase: "Project Completion",
        date: "May 2019",
        description: "Final inspections, testing, and opening to traffic.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1477936821694-ec4233a9a1a0?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1506862047911-10d183b3b0b0?q=80&w=1374&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505942231292-8fe7143fb5b8?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1514924013411-cbf25faa35bb?q=80&w=1490&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 4,
        name: "Metro Line Extension",
        category: "Infrastructure",
        location: "North District, Building City",
        year: "2020",
        image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1374&auto=format&fit=crop",
      },
      {
        id: 15,
        name: "Airport Terminal Expansion",
        category: "Infrastructure",
        location: "International Airport, Building City",
        year: "2021",
        image: "https://images.unsplash.com/photo-1530521954074-e64f6810b32d?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 16,
        name: "Smart City Grid Upgrade",
        category: "Infrastructure",
        location: "Citywide, Building City",
        year: "2022",
        image: "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 8,
    name: "Tech Innovation Hub",
    category: "Commercial",
    location: "Innovation District, Building City",
    year: "2021",
    description: "A cutting-edge office complex designed for technology companies, startups, and research facilities.",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=1374&auto=format&fit=crop",
    client: "Innovation Properties LLC",
    size: "280,000 sq ft",
    value: "$75 million",
    fullDescription:
      "The Tech Innovation Hub is a state-of-the-art office complex designed specifically for technology companies, startups, and research organizations. The campus consists of three interconnected buildings with flexible office spaces, collaborative areas, and specialized facilities like prototype labs and testing centers. The design emphasizes innovation, collaboration, and sustainability, with open floor plans, abundant natural light, and cutting-edge technology infrastructure throughout. The complex includes shared amenities such as conference centers, fitness facilities, and dining options to create a complete work ecosystem for tenants.",
    features: [
      "280,000 square feet of flexible office and research space",
      "Three interconnected buildings with varying floor plans",
      "Prototype labs and testing facilities",
      "High-speed fiber optic network throughout",
      "Collaborative spaces and informal meeting areas",
      "Conference center with advanced presentation technology",
      "Fitness center and wellness facilities",
      "On-site dining options and coffee shops",
      "Sustainable design with LEED Platinum certification",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "March 2018 - December 2018",
        description: "Architectural design, technology planning, and permit approvals.",
      },
      {
        phase: "Site Preparation",
        date: "January 2019 - April 2019",
        description: "Site clearing, grading, and utility infrastructure installation.",
      },
      {
        phase: "Foundation Work",
        date: "May 2019 - August 2019",
        description: "Foundation construction for all three buildings.",
      },
      {
        phase: "Structural Construction",
        date: "September 2019 - May 2020",
        description: "Structural framework and floor installation for all buildings.",
      },
      {
        phase: "Exterior Completion",
        date: "June 2020 - September 2020",
        description: "Exterior cladding, windows, and roofing installation.",
      },
      {
        phase: "Interior Fitout",
        date: "October 2020 - January 2021",
        description: "Interior construction, technology infrastructure, and finishing work.",
      },
      {
        phase: "Technology Integration",
        date: "February 2021 - March 2021",
        description: "Installation and testing of advanced technology systems.",
      },
      {
        phase: "Project Completion",
        date: "April 2021",
        description: "Final inspections, certification, and tenant move-ins.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1469&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1469&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517502884422-41eaead166d4?q=80&w=1525&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 1,
        name: "City Center Office Complex",
        category: "Commercial",
        location: "Downtown, Building City",
        year: "2023",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 5,
        name: "Green Valley Shopping Mall",
        category: "Commercial",
        location: "Green Valley, Building City",
        year: "2019",
        image: "https://images.unsplash.com/photo-1519567770579-c2fc5e9ca471?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 10,
        name: "Waterfront Business Center",
        category: "Commercial",
        location: "Harbor District, Building City",
        year: "2022",
        image: "https://images.unsplash.com/photo-1577760258779-e787a1733016?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 9,
    name: "Urban Loft Apartments",
    category: "Residential",
    location: "Arts District, Building City",
    year: "2020",
    description: "Converted warehouse lofts featuring industrial design elements and modern amenities.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1470&auto=format&fit=crop",
    client: "Urban Living Developers",
    size: "120,000 sq ft",
    value: "$40 million",
    fullDescription:
      "The Urban Loft Apartments project involved the adaptive reuse of a historic warehouse in the Arts District, transforming it into 60 unique loft-style residences. The development preserves the industrial character of the original structure while incorporating modern amenities and sustainable features. Each loft features high ceilings, exposed brick walls, original timber beams, and large factory windows that flood the spaces with natural light. The ground floor includes retail spaces, art galleries, and a coffee shop, creating a vibrant mixed-use environment that contributes to the cultural fabric of the neighborhood.",
    features: [
      "60 unique loft apartments ranging from 800 to 2,000 sq ft",
      "Preserved industrial elements including brick walls and timber beams",
      "Oversized windows and high ceilings in all units",
      "Modern kitchens with premium appliances",
      "Rooftop terrace with city views",
      "Community art gallery and event space",
      "Ground floor retail and dining options",
      "Secure parking with EV charging stations",
      "Bike storage and repair station",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "January 2018 - July 2018",
        description: "Architectural design, historic preservation planning, and permit approvals.",
      },
      {
        phase: "Building Assessment",
        date: "August 2018 - September 2018",
        description: "Structural assessment and hazardous material remediation.",
      },
      {
        phase: "Structural Reinforcement",
        date: "October 2018 - February 2019",
        description: "Reinforcement of the existing structure to meet modern building codes.",
      },
      {
        phase: "Core & Shell Renovation",
        date: "March 2019 - August 2019",
        description: "Renovation of the building envelope, windows, and core infrastructure.",
      },
      {
        phase: "Interior Construction",
        date: "September 2019 - January 2020",
        description: "Construction of individual loft units and common areas.",
      },
      {
        phase: "Finishing Work",
        date: "February 2020 - April 2020",
        description: "Installation of finishes, fixtures, and appliances.",
      },
      {
        phase: "Retail Spaces",
        date: "March 2020 - May 2020",
        description: "Completion of ground floor retail and commercial spaces.",
      },
      {
        phase: "Project Completion",
        date: "June 2020",
        description: "Final inspections, certification, and resident move-ins.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1380&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?q=80&w=1471&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-61dc36dc98c8?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1470&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 2,
        name: "Riverside Apartments",
        category: "Residential",
        location: "Riverside District, Building City",
        year: "2022",
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 6,
        name: "Sunset Heights Condominiums",
        category: "Residential",
        location: "West Hills, Building City",
        year: "2018",
        image: "https://images.unsplash.com/photo-1580041065738-e72023775cdc?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 12,
        name: "Parkview Residences",
        category: "Residential",
        location: "Central Park Area, Building City",
        year: "2021",
        image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 10,
    name: "Waterfront Business Center",
    category: "Commercial",
    location: "Harbor District, Building City",
    year: "2022",
    description: "A mixed-use business center with offices, retail, and dining options along the waterfront.",
    image: "https://images.unsplash.com/photo-1577760258779-e787a1733016?q=80&w=1470&auto=format&fit=crop",
    client: "Harbor Development Corporation",
    size: "350,000 sq ft",
    value: "$110 million",
    fullDescription:
      "The Waterfront Business Center is a premier mixed-use development located in the revitalized Harbor District. The project consists of three buildings arranged around a central plaza that opens to the waterfront promenade. The complex includes Class A office spaces, retail stores, restaurants, and public amenities. The architectural design draws inspiration from maritime themes while incorporating modern elements and sustainable features. Large windows and terraces provide stunning water views from all levels, while the public spaces create a seamless connection between the development and the waterfront.",
    features: [
      "350,000 square feet of mixed-use space across three buildings",
      "200,000 square feet of Class A office space",
      "50,000 square feet of retail and dining space",
      "Waterfront promenade with public seating and art installations",
      "Central plaza with water features and event space",
      "Rooftop terraces with harbor views",
      "Underground parking for 500 vehicles",
      "Marina access with private boat slips",
      "LEED Gold certified sustainable design",
    ],
    timeline: [
      {
        phase: "Planning & Design",
        date: "January 2019 - September 2019",
        description: "Architectural design, waterfront integration planning, and permit approvals.",
      },
      {
        phase: "Site Preparation",
        date: "October 2019 - January 2020",
        description: "Site clearing, shoreline stabilization, and utility infrastructure installation.",
      },
      {
        phase: "Foundation Work",
        date: "February 2020 - June 2020",
        description: "Foundation construction for all three buildings and underground parking.",
      },
      {
        phase: "Structural Construction",
        date: "July 2020 - March 2021",
        description: "Structural framework and floor installation for all buildings.",
      },
      {
        phase: "Exterior Completion",
        date: "April 2021 - August 2021",
        description: "Exterior cladding, windows, and roofing installation.",
      },
      {
        phase: "Interior Fitout",
        date: "September 2021 - December 2021",
        description: "Interior construction, common areas, and tenant spaces.",
      },
      {
        phase: "Waterfront Development",
        date: "October 2021 - February 2022",
        description: "Construction of the waterfront promenade, plaza, and landscaping.",
      },
      {
        phase: "Project Completion",
        date: "March 2022",
        description: "Final inspections, certification, and tenant move-ins.",
      },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?q=80&w=1474&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1622547748225-3fc4abd2cca0?q=80&w=1469&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1469&auto=format&fit=crop",
    ],
    relatedProjects: [
      {
        id: 1,
        name: "City Center Office Complex",
        category: "Commercial",
        location: "Downtown, Building City",
        year: "2023",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 5,
        name: "Green Valley Shopping Mall",
        category: "Commercial",
        location: "Green Valley, Building City",
        year: "2019",
        image: "https://images.unsplash.com/photo-1519567770579-c2fc5e9ca471?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 8,
        name: "Tech Innovation Hub",
        category: "Commercial",
        location: "Innovation District, Building City",
        year: "2021",
        image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=1374&auto=format&fit=crop",
      },
    ],
  },
]

// Apartments data
export const apartments = [
  {
    id: 1,
    name: "Luxury Penthouse",
    location: "Downtown, Building City",
    price: "$850,000",
    bedrooms: 3,
    bathrooms: 2,
    area: "2,200 sq ft",
    description: "Stunning penthouse with panoramic city views, premium finishes, and private terrace.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1470&auto=format&fit=crop",
    type: "Penthouse",
    yearBuilt: "2021",
    status: "For Sale",
    parking: "2 Spaces",
    fullDescription:
      "This spectacular penthouse offers the ultimate in luxury urban living. Located on the top floor of a premier downtown building, this residence features 3 spacious bedrooms, 2 designer bathrooms, and an open-concept living area with floor-to-ceiling windows that showcase breathtaking panoramic views of the city skyline. The gourmet kitchen is equipped with top-of-the-line appliances, custom cabinetry, and a large center island. The expansive private terrace provides an additional 500 sq ft of outdoor living space, perfect for entertaining or relaxing while enjoying the sunset over the city. Premium finishes throughout include hardwood floors, marble countertops, and custom lighting. Building amenities include 24/7 concierge, fitness center, resident lounge, and secure parking.",
    features: [
      "Floor-to-ceiling windows with panoramic city views",
      "Private 500 sq ft terrace",
      "Gourmet kitchen with premium appliances",
      "Master suite with walk-in closet and spa bathroom",
      "Custom lighting and home automation system",
      "Hardwood floors throughout",
      "10-foot ceilings",
      "Central heating and air conditioning",
      "In-unit laundry room",
      "24/7 concierge service",
      "Fitness center and resident lounge",
      "Secure parking garage",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1380&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448075-57d0285fc80b?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-61dc36dc98c8?q=80&w=1470&auto=format&fit=crop",
    ],
    floorPlan: "https://images.unsplash.com/photo-1580413597377-5698a5d5e9d6?q=80&w=1374&auto=format&fit=crop",
    similarProperties: [
      {
        id: 4,
        name: "Sky Loft",
        location: "Central District, Building City",
        price: "$580,000",
        bedrooms: 2,
        bathrooms: 2,
        area: "1,800 sq ft",
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 7,
        name: "Executive Apartment",
        location: "Financial District, Building City",
        price: "$750,000",
        bedrooms: 2,
        bathrooms: 2,
        area: "1,900 sq ft",
        image: "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 10,
        name: "Skyline Penthouse",
        location: "North Tower, Downtown",
        price: "$920,000",
        bedrooms: 3,
        bathrooms: 3,
        area: "2,400 sq ft",
        image: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 2,
    name: "Riverside Suite",
    location: "Riverside District, Building City",
    price: "$450,000",
    bedrooms: 2,
    bathrooms: 2,
    area: "1,500 sq ft",
    description: "Beautiful apartment with river views, modern design, and access to premium amenities.",
    image: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?q=80&w=1470&auto=format&fit=crop",
    type: "Apartment",
    yearBuilt: "2020",
    status: "For Sale",
    parking: "1 Space",
    fullDescription:
      "Experience waterfront living at its finest in this elegant Riverside Suite. This 2-bedroom, 2-bathroom apartment offers 1,500 square feet of thoughtfully designed living space with spectacular views of the river. The open floor plan features a spacious living and dining area that opens to a private balcony where you can enjoy the peaceful river scenery. The chef's kitchen includes stainless steel appliances, quartz countertops, and custom cabinetry. The master suite includes a walk-in closet and an ensuite bathroom with a soaking tub and separate shower. The second bedroom is perfect for guests or a home office. Located in the prestigious Riverside development, residents enjoy access to a range of premium amenities including a waterfront pool, fitness center, resident lounge, and landscaped gardens. The building's central location provides easy access to dining, shopping, and entertainment options.",
    features: [
      "Panoramic river views",
      "Private balcony",
      "Chef's kitchen with premium appliances",
      "Master suite with walk-in closet",
      "Ensuite bathroom with soaking tub",
      "Hardwood floors throughout",
      "In-unit washer and dryer",
      "Central heating and air conditioning",
      "Waterfront swimming pool",
      "Fitness center with yoga studio",
      "Resident lounge and entertainment space",
      "Secure access and parking",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1560185008-a33f5c7b1844?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1474&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1470&auto=format&fit=crop",
    ],
    floorPlan: "https://images.unsplash.com/photo-1580413597377-5698a5d5e9d6?q=80&w=1374&auto=format&fit=crop",
    similarProperties: [
      {
        id: 5,
        name: "Waterfront Condo",
        location: "Harbor District, Building City",
        price: "$495,000",
        bedrooms: 2,
        bathrooms: 2,
        area: "1,600 sq ft",
        image: "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 8,
        name: "Riverside Loft",
        location: "Riverside District, Building City",
        price: "$420,000",
        bedrooms: 1,
        bathrooms: 1.5,
        area: "1,200 sq ft",
        image: "https://images.unsplash.com/photo-1560448204-61dc36dc98c8?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 11,
        name: "River View Apartment",
        location: "Riverside District, Building City",
        price: "$475,000",
        bedrooms: 2,
        bathrooms: 2,
        area: "1,550 sq ft",
        image: "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 3,
    name: "Garden Apartment",
    location: "Green Valley, Building City",
    price: "$320,000",
    bedrooms: 1,
    bathrooms: 1,
    area: "950 sq ft",
    description: "Cozy apartment with private garden access, perfect for nature lovers and small families.",
    image: "https://images.unsplash.com/photo-1560185008-cde436f6a4d0?q=80&w=1470&auto=format&fit=crop",
    type: "Garden Apartment",
    yearBuilt: "2019",
    status: "For Sale",
    parking: "1 Space",
    fullDescription:
      "This charming Garden Apartment offers a unique blend of urban convenience and natural tranquility. The 950 square foot residence features one bedroom, one bathroom, and a bright, open living area that flows seamlessly to a private garden patio. The well-appointed kitchen includes stainless steel appliances, granite countertops, and ample storage space. The bedroom is generously sized with a large closet and garden views. The highlight of this property is the private garden area, providing approximately 300 square feet of outdoor living space that's perfect for gardening, entertaining, or simply relaxing in nature. Located in the peaceful Green Valley neighborhood, this apartment offers a serene setting while still being just minutes from shopping, dining, and transportation options. The building features secure entry, dedicated parking, and a community rooftop terrace with panoramic views.",
    features: [
      "Private garden patio",
      "Open-concept living area",
      "Kitchen with stainless steel appliances",
      "Hardwood floors throughout",
      "Large bedroom with garden views",
      "In-unit washer and dryer",
      "Energy-efficient windows and appliances",
      "Secure building entry",
      "Dedicated parking space",
      "Community rooftop terrace",
      "Pet-friendly building",
      "Storage unit included",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1560185008-a33f5c7b1844?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1470&auto=format&fit=crop",
    ],
    floorPlan: "https://images.unsplash.com/photo-1580413597377-5698a5d5e9d6?q=80&w=1374&auto=format&fit=crop",
    similarProperties: [
      {
        id: 6,
        name: "Park View Studio",
        location: "Green Valley, Building City",
        price: "$280,000",
        bedrooms: 0,
        bathrooms: 1,
        area: "650 sq ft",
        image: "https://images.unsplash.com/photo-1560448075-d03b1ce5618b?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 9,
        name: "Garden Terrace Home",
        location: "Green Valley, Building City",
        price: "$350,000",
        bedrooms: 1,
        bathrooms: 1,
        area: "1,000 sq ft",
        image: "https://images.unsplash.com/photo-1600585154526-990dced4db3d?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 12,
        name: "Courtyard Apartment",
        location: "Green Valley, Building City",
        price: "$335,000",
        bedrooms: 1,
        bathrooms: 1,
        area: "975 sq ft",
        image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 4,
    name: "Sky Loft",
    location: "Central District, Building City",
    price: "$580,000",
    bedrooms: 2,
    bathrooms: 2,
    area: "1,800 sq ft",
    description: "Modern loft-style apartment with high ceilings, open floor plan, and city skyline views.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1470&auto=format&fit=crop",
    type: "Loft",
    yearBuilt: "2018",
    status: "For Sale",
    parking: "1 Space",
    fullDescription:
      "Experience the height of urban sophistication in this stunning Sky Loft. This 1,800 square foot loft-style residence features soaring 14-foot ceilings, expansive windows, and an open floor plan that maximizes space and light. The two-bedroom, two-bathroom layout offers both functionality and style, with a flexible design that can be customized to your lifestyle. The gourmet kitchen is a chef's dream with high-end appliances, custom cabinetry, and a large island that's perfect for entertaining. The primary suite includes a spacious bedroom area, custom walk-in closet, and a luxurious bathroom with a soaking tub and separate shower. The second bedroom can serve as a guest room, home office, or media room. Throughout the loft, industrial-inspired elements like exposed ductwork and concrete pillars are balanced with warm wood finishes and contemporary fixtures. Floor-to-ceiling windows frame spectacular views of the city skyline, while automated blinds provide privacy when desired.",
    features: [
      "14-foot ceilings throughout",
      "Floor-to-ceiling windows with city views",
      "Open floor plan with flexible living spaces",
      "Gourmet kitchen with high-end appliances",
      "Custom cabinetry and built-ins",
      "Hardwood and polished concrete floors",
      "Spa-inspired bathrooms",
      "Custom lighting system",
      "In-unit laundry room",
      "Building amenities including fitness center and roof deck",
      "Secure entry and parking",
      "Storage unit included",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?q=80&w=1471&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?q=80&w=1476&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-61dc36dc98c8?q=80&w=1470&auto=format&fit=crop",
    ],
    floorPlan: "https://images.unsplash.com/photo-1580413597377-5698a5d5e9d6?q=80&w=1374&auto=format&fit=crop",
    similarProperties: [
      {
        id: 1,
        name: "Luxury Penthouse",
        location: "Downtown, Building City",
        price: "$850,000",
        bedrooms: 3,
        bathrooms: 2,
        area: "2,200 sq ft",
        image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 7,
        name: "Executive Apartment",
        location: "Financial District, Building City",
        price: "$750,000",
        bedrooms: 2,
        bathrooms: 2,
        area: "1,900 sq ft",
        image: "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 9,
        name: "Urban Loft",
        location: "Arts District, Building City",
        price: "$540,000",
        bedrooms: 1,
        bathrooms: 1.5,
        area: "1,600 sq ft",
        image: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?q=80&w=1471&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 5,
    name: "Family Townhouse",
    location: "Suburban Area, Building City",
    price: "$620,000",
    bedrooms: 3,
    bathrooms: 2.5,
    area: "2,100 sq ft",
    description: "Spacious townhouse with multiple levels, perfect for growing families seeking comfort and space.",
    image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?q=80&w=1470&auto=format&fit=crop",
    type: "Townhouse",
    yearBuilt: "2017",
    status: "For Sale",
    parking: "2-Car Garage",
    fullDescription:
      "This beautiful Family Townhouse offers the perfect blend of space, comfort, and convenience for growing families. Spanning three levels and 2,100 square feet, this residence features three bedrooms, two and a half bathrooms, and versatile living spaces designed for modern family life. The main level includes an open-concept living and dining area that flows into a gourmet kitchen with a breakfast nook. Large windows throughout fill the space with natural light, while a private patio off the dining area provides outdoor living space. The upper level includes a primary suite with a walk-in closet and ensuite bathroom, plus two additional bedrooms and a full bathroom. The finished lower level can serve as a family room, home office, or play area, with direct access to the attached two-car garage. Located in a family-friendly neighborhood, this townhouse is just minutes from parks, schools, shopping centers, and major transportation routes.",
    features: [
      "Three-level townhouse with 2,100 square feet",
      "Open-concept main level with living, dining, and kitchen areas",
      "Gourmet kitchen with stainless steel appliances",
      "Private patio for outdoor entertaining",
      "Primary suite with walk-in closet and ensuite bathroom",
      "Two additional bedrooms with shared bathroom",
      "Finished lower level for flexible use",
      "Attached two-car garage with storage",
      "Energy-efficient windows and HVAC system",
      "Hardwood floors on main level",
      "Community amenities including pool and playground",
      "Close to schools, parks, and shopping",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753104-685f4f24cb4d?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=1470&auto=format&fit=crop",
    ],
    floorPlan: "https://images.unsplash.com/photo-1580413597377-5698a5d5e9d6?q=80&w=1374&auto=format&fit=crop",
    similarProperties: [
      {
        id: 13,
        name: "Suburban Townhome",
        location: "Suburban Area, Building City",
        price: "$590,000",
        bedrooms: 3,
        bathrooms: 2,
        area: "1,950 sq ft",
        image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 14,
        name: "Family Residence",
        location: "Suburban Area, Building City",
        price: "$650,000",
        bedrooms: 4,
        bathrooms: 3,
        area: "2,300 sq ft",
        image: "https://images.unsplash.com/photo-1600607687644-c7f34c43d2fd?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 15,
        name: "Modern Townhouse",
        location: "Suburban Area, Building City",
        price: "$610,000",
        bedrooms: 3,
        bathrooms: 2.5,
        area: "2,050 sq ft",
        image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
  {
    id: 6,
    name: "Studio Apartment",
    location: "Arts District, Building City",
    price: "$250,000",
    bedrooms: 0,
    bathrooms: 1,
    area: "650 sq ft",
    description: "Compact and stylish studio apartment in the vibrant arts district, perfect for young professionals.",
    image: "https://images.unsplash.com/photo-1560448075-d03b1ce5618b?q=80&w=1470&auto=format&fit=crop",
    type: "Studio",
    yearBuilt: "2019",
    status: "For Sale",
    parking: "Available for Purchase",
    fullDescription:
      "This stylish Studio Apartment offers efficient, modern living in the heart of the vibrant Arts District. The thoughtfully designed 650 square foot space maximizes functionality without sacrificing style. The open-concept layout features distinct living, sleeping, and dining areas that flow seamlessly together. The contemporary kitchen includes stainless steel appliances, quartz countertops, and ample storage. The bathroom features a walk-in shower with designer tiles and modern fixtures. Large windows fill the space with natural light and provide views of the neighborhood's artistic character. Smart storage solutions throughout help maximize the living space. Located in a modern building in the Arts District, residents enjoy proximity to galleries, restaurants, cafes, and boutiques. Building amenities include a rooftop terrace, fitness center, and secure entry. This studio is perfect for young professionals, artists, or investors looking for a property in a dynamic, growing neighborhood.",
    features: [
      "Efficient 650 square foot open-concept design",
      "Modern kitchen with stainless steel appliances",
      "Designer bathroom with walk-in shower",
      "Large windows with neighborhood views",
      "Smart storage solutions throughout",
      "Hardwood floors",
      "In-unit washer and dryer",
      "Central heating and air conditioning",
      "Building rooftop terrace with city views",
      "Fitness center access",
      "Secure building entry",
      "Optional parking available for purchase",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1560448075-57d0285fc80b?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448075-cae88c143143?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-61dc36dc98c8?q=80&w=1470&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1470&auto=format&fit=crop",
    ],
    floorPlan: "https://images.unsplash.com/photo-1580413597377-5698a5d5e9d6?q=80&w=1374&auto=format&fit=crop",
    similarProperties: [
      {
        id: 16,
        name: "Artist's Loft",
        location: "Arts District, Building City",
        price: "$275,000",
        bedrooms: 0,
        bathrooms: 1,
        area: "700 sq ft",
        image: "https://images.unsplash.com/photo-1560448075-cae88c143143?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 17,
        name: "Micro Apartment",
        location: "Downtown, Building City",
        price: "$230,000",
        bedrooms: 0,
        bathrooms: 1,
        area: "500 sq ft",
        image: "https://images.unsplash.com/photo-1560448075-57d0285fc80b?q=80&w=1470&auto=format&fit=crop",
      },
      {
        id: 18,
        name: "Urban Studio",
        location: "Central District, Building City",
        price: "$265,000",
        bedrooms: 0,
        bathrooms: 1,
        area: "675 sq ft",
        image: "https://images.unsplash.com/photo-1560448204-61dc36dc98c8?q=80&w=1470&auto=format&fit=crop",
      },
    ],
  },
]

// Helper functions to get data
export function getAllProjects() {
  return projects
}

export function getProjectById(id: number) {
  return projects.find((project) => project.id === id)
}

export function getAllApartments() {
  return apartments
}

export function getApartmentById(id: number) {
  return apartments.find((apartment) => apartment.id === id)
}
